name: Desafio API QA - Testes Automatizados

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-24.04  # Versão explícita do Ubuntu
    strategy:
      matrix:
        python-version: ["3.12"]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4  # Atualizado para v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5  # Atualizado para v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install behave requests

      - name: Run API tests with Behave
        run: |
          PYTHONPATH=. behave --format progress2 --tags=-wip

      - name: Upload test reports
        uses: actions/upload-artifact@v4  # Atualizado para v4
        if: always()
        with:
          name: test-results-${{ matrix.python-version }}
          path: |
            reports/
            test-results/