name: Desafio API QA - Testes Automatizados com Allure

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        python-version: ["3.12"]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install behave allure-behave

      - name: Run API tests with Allure Behave
        run: |
          mkdir -p allure-results
          PYTHONPATH=. behave -f allure_behave.formatter:AllureFormatter -o allure-results features/

      - name: Generate Allure Report (HTML)
        run: |
          sudo apt-get update && sudo apt-get install -y openjdk-17-jre
          wget https://github.com/allure-framework/allure2/releases/latest/download/allure-2.27.0.tgz
          tar -xzf allure-2.27.0.tgz
          ./allure-2.27.0/bin/allure generate allure-results --clean -o allure-report

      - name: Upload Allure HTML report as artifact
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: allure-report
          path: allure-report
