name: Desafio API QA - Testes Automatizados

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.12"]
        # Adicione outras versões se necessário: ["3.10", "3.11", "3.12"]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip'  # Habilita cache de dependências

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install behave requests  # Garante instalação explícita

      - name: Run API tests with Behave
        run: |
          PYTHONPATH=. behave --format progress2 --tags=-wip
          # progress2 mostra melhor visualização dos testes
          # --tags=-wip ignora cenários marcados como work-in-progress

      - name: Upload test reports
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: test-results-${{ matrix.python-version }}
          path: |
            reports/
            test-results/
